# Generated by Django 3.2.8 on 2021-10-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_enterprise',
            name='login_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='identification',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='user_enterprise',
            name='identification',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='user_enterprise',
            name='phone',
            field=models.BigIntegerField(unique=True),
        ),
    ]
