# Generated by Django 3.2.8 on 2021-10-26 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211026_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_enterprise',
            name='role_enterprise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.role_enterprise'),
        ),
    ]
