# Generated by Django 3.2.8 on 2021-10-27 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_enterprise_role_enterprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_enterprise',
            name='login_state',
            field=models.BooleanField(default=True),
        ),
    ]
