# Generated by Django 3.2.8 on 2021-11-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_enterprise_login_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='traceability_user',
            name='element',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traceability_user',
            name='group',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
