# Generated by Django 3.2.8 on 2021-11-02 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211102_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traceability_user',
            name='action',
            field=models.IntegerField(),
        ),
    ]
