# Generated by Django 3.2.8 on 2021-11-03 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        # ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0006_alter_traceability_user_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='permit',
            name='auth_permission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.permission'),
        ),
        migrations.AddField(
            model_name='permit',
            name='view',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='permit',
            unique_together={('auth_permission', 'view')},
        ),
        migrations.CreateModel(
            name='Permit_Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.enterprise')),
                ('permit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.permit')),
            ],
            options={
                'unique_together': {('enterprise', 'permit_type')},
            },
        ),
        migrations.RemoveField(
            model_name='permit',
            name='state',
        ),
        migrations.AlterField(
            model_name='permit_role',
            name='permit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.permit_enterprise'),
        ),
    ]
