# Generated by Django 3.2.8 on 2021-11-08 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_traceability_user_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sms_Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.IntegerField()),
                ('phone_user', models.IntegerField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('state', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
