# Generated by Django 3.2.8 on 2021-11-08 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_sms_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms_token',
            name='phone_user',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='sms_token',
            name='token',
            field=models.BigIntegerField(),
        ),
    ]
