# Generated by Django 3.2.8 on 2021-11-04 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_user_enterprise_role_enterprise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_enterprise',
            name='role_enterprise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.role_enterprise'),
        ),
    ]
