# Generated by Django 3.2.8 on 2021-11-05 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20211103_1553'),
        ('api', '0008_alter_user_enterprise_role_enterprise'),
    ]

    operations = [
    ]
