# Generated by Django 3.2.8 on 2021-11-05 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_merge_20211105_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='permit_enterprise',
            name='modify_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
