# Generated by Django 3.2.8 on 2021-11-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_permit_enterprise_modify_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='role_enterprise',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
