# Generated by Django 3.2.8 on 2021-11-09 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20211108_1737'),
        ('api', '0010_permit_enterprise_modify_date'),
    ]

    operations = [
    ]
