# Generated by Django 3.2.8 on 2021-11-09 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_merge_20211109_1740'),
        ('api', '0011_role_enterprise_is_admin'),
    ]

    operations = [
    ]
