# Generated by Django 3.2.8 on 2021-11-12 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_merge_20211109_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option_field',
            name='form_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.form_field'),
        ),
    ]
