# Generated by Django 3.2.8 on 2021-11-12 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_merge_20211109_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='type_device',
            name='color',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='type_device',
            name='icon',
            field=models.IntegerField(null=True),
        ),
    ]
