# Generated by Django 3.2.8 on 2021-11-16 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_option_field_form_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_enterprise',
            name='consecutive',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Form_Field_Consecutive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=True)),
                ('form_enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.form_enterprise')),
                ('form_field_get', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_field_consecutive_padre', to='api.form_field')),
                ('form_field_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.form_field')),
            ],
        ),
        migrations.CreateModel(
            name='Form_Consecutive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('state', models.BooleanField(default=True)),
                ('form_enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.form_enterprise')),
            ],
        ),
    ]
