# Generated by Django 3.2.8 on 2021-11-12 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20211111_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='type_device',
            name='enterprise',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.enterprise'),
            preserve_default=False,
        ),
    ]
