# Generated by Django 3.2.8 on 2021-11-17 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20211116_1446'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Form_Consecutive',
        ),
    ]
