# Generated by Django 3.2.8 on 2021-11-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_type_device_enterprise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type_device',
            name='icon',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
