# Generated by Django 3.2.8 on 2021-11-17 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_delete_form_consecutive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form_Consecutive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('state', models.BooleanField(default=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.form_enterprise')),
                ('form_enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_consecutive_padre', to='api.form_enterprise')),
            ],
        ),
    ]
