# Generated by Django 3.2.8 on 2021-11-17 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_type_device_icon'),
        ('api', '0016_form_consecutive'),
    ]

    operations = [
    ]
