# Generated by Django 3.2.8 on 2021-11-18 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_merge_20211117_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_enterprise',
            name='register_platform',
            field=models.IntegerField(default=0),
        ),
    ]
