# Generated by Django 3.2.8 on 2021-11-19 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_user_enterprise_register_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter_Validate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=50)),
                ('state', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Form_Field_Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('state', models.BooleanField(default=True)),
                ('form_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.form_field')),
                ('parameter_validate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.parameter_validate')),
            ],
        ),
    ]
