# Generated by Django 3.2.8 on 2021-12-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_form_field_parameter_parameter_validate'),
    ]

    operations = [
        migrations.AddField(
            model_name='device_enterprise',
            name='mac',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
