# Generated by Django 3.2.8 on 2021-12-01 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_form_field_parameter_parameter_validate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer_Consecutive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('state', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user_enterprise')),
                ('form_consecutive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.form_enterprise')),
            ],
        ),
        migrations.AddField(
            model_name='answer_field',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='answer_form',
            name='consecutive',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Answer_Form_Consecutive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=True)),
                ('answer_consecutive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.answer_consecutive')),
                ('answer_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.answer_form')),
            ],
        ),
    ]
