# Generated by Django 3.2.8 on 2021-12-02 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20211201_2157'),
        ('api', '0020_device_enterprise_mac'),
    ]

    operations = [
    ]
