# Generated by Django 3.2.8 on 2021-12-04 17:35

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0021_merge_20211202_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Massive_File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.FileField(blank=True, null=True, upload_to=api.models.template_directory_path)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('type', models.IntegerField(default=0)),
                ('amount', models.IntegerField()),
                ('success', models.IntegerField(default=0)),
                ('error', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.enterprise')),
            ],
        ),
        migrations.CreateModel(
            name='Massive_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('massive_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.massive_file')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Massive_Errors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField()),
                ('data', models.CharField(max_length=300)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('massive_user_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.massive_file')),
            ],
        ),
        migrations.CreateModel(
            name='Massive_Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.device_enterprise')),
                ('massive_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.massive_file')),
            ],
        ),
    ]
