# Generated by Django 3.2.8 on 2021-12-04 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_massive_device_massive_errors_massive_file_massive_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='massive_errors',
            old_name='massive_user_file',
            new_name='massive_file',
        ),
    ]
