# Generated by Django 3.2.8 on 2021-12-05 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_rename_massive_user_file_massive_errors_massive_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer_form',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='answer_form',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
