# Generated by Django 3.2.8 on 2021-12-05 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20211205_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role_form',
            name='delete',
        ),
        migrations.RemoveField(
            model_name='role_form',
            name='edit',
        ),
        migrations.RemoveField(
            model_name='role_form',
            name='fill',
        ),
        migrations.RemoveField(
            model_name='role_form',
            name='view',
        ),
        migrations.CreateModel(
            name='User_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('state', models.BooleanField(default=True)),
                ('form_enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.form_enterprise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user_enterprise')),
            ],
        ),
    ]
