# Generated by Django 3.2.8 on 2021-12-06 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20211205_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role_form',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.role_enterprise'),
        ),
    ]
