# Generated by Django 3.2.8 on 2021-12-11 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_role_form_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='restrictive_lists',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='api.user_enterprise'),
            preserve_default=False,
        ),
    ]
