# Generated by Django 3.2.8 on 2021-12-11 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20211210_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='restrictive_lists',
            field=models.CharField(max_length=60000),
        ),
    ]
