# Generated by Django 3.2.8 on 2021-12-13 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_profile_restrictive_lists'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='token_autorization',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
