# Generated by Django 3.2.8 on 2021-12-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_profile_token_autorization'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer_consecutive',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='answer_consecutive',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='answer_consecutive',
            name='online',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='answer_consecutive',
            name='source',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='answer_consecutive',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
