# Generated by Django 3.2.8 on 2021-12-17 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20211214_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massive_user',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user_enterprise'),
        ),
    ]
