# Generated by Django 3.2.8 on 2022-01-12 18:00

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_order_enterprise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_path', models.FileField(blank=True, null=True, upload_to=api.models.route_directory_path)),
                ('status', models.IntegerField()),
                ('state', models.BooleanField(default=True)),
                ('massive_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.massive_file')),
            ],
        ),
        migrations.DeleteModel(
            name='Order_Enterprise',
        ),
    ]
