# Generated by Django 3.2.8 on 2022-01-14 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20220112_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_enterprise',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
