# Generated by Django 3.2.8 on 2022-01-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20220117_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='location_enterprise',
            name='city',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location_enterprise',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project_enterprise',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
