# Generated by Django 3.2.8 on 2022-01-26 16:36

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_form_enterprise_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_enterprise',
            name='digital',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Form_Digital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.FileField(blank=True, null=True, upload_to=api.models.digital_directory_path)),
                ('status', models.IntegerField(default=0)),
                ('form_enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.form_enterprise')),
            ],
        ),
    ]
