# Generated by Django 3.2.8 on 2022-01-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20220117_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='location_enterprise',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project_enterprise',
            name='description',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='project_enterprise',
            name='identifier',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='project_enterprise',
            unique_together={('enterprise', 'identifier')},
        ),
    ]
