# Generated by Django 3.2.8 on 2022-01-27 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20220126_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Digital_Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.IntegerField()),
                ('left', models.CharField(max_length=20)),
                ('top', models.CharField(max_length=20)),
                ('font', models.CharField(max_length=15)),
                ('size', models.IntegerField()),
                ('color', models.CharField(max_length=7)),
                ('bold', models.BooleanField(default=False)),
                ('italic', models.BooleanField(default=False)),
                ('underline', models.BooleanField(default=False)),
                ('width', models.CharField(max_length=5)),
                ('height', models.CharField(max_length=5)),
                ('option', models.IntegerField(default=0)),
                ('option_value', models.IntegerField(null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('state', models.BooleanField(default=True)),
                ('form_digital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.form_digital')),
                ('form_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.form_field')),
            ],
        ),
    ]
