# Generated by Django 3.2.8 on 2022-01-21 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20220121_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='location_enterprise',
            name='country',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
