# Generated by Django 3.2.8 on 2022-01-28 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_digital_field'),
        ('api', '0037_location_enterprise_country'),
    ]

    operations = [
    ]
