# Generated by Django 3.2.8 on 2022-01-28 07:32

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_merge_20220128_0220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address_Locality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.IntegerField(null=True)),
                ('state', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Address_Neighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('state', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Address_UPZ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.IntegerField()),
                ('state', models.BooleanField(default=True)),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.address_locality')),
            ],
        ),
        migrations.CreateModel(
            name='Address_Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('state', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.IntegerField(null=True)),
                ('state', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.IntegerField()),
                ('state', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enterprise_Process_State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('order', models.IntegerField()),
                ('custom', models.BooleanField(default=False)),
                ('cancel', models.BooleanField(default=False)),
                ('state', models.BooleanField(default=True)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.enterprise')),
            ],
        ),
        migrations.CreateModel(
            name='Enterprise_Processs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.CharField(default='', max_length=256)),
                ('state', models.BooleanField(default=True)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.enterprise')),
            ],
        ),
        migrations.CreateModel(
            name='Enterprise_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now_add=True)),
                ('state', models.BooleanField(default=True)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.enterprise')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.IntegerField()),
                ('state', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.country')),
            ],
        ),
        migrations.CreateModel(
            name='Service_Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('address', models.CharField(max_length=128)),
                ('address_normalized', models.CharField(max_length=128)),
                ('comment', models.CharField(max_length=200)),
                ('comment_address', models.CharField(max_length=200)),
                ('user_name', models.CharField(max_length=128)),
                ('user_email', models.CharField(max_length=50)),
                ('user_phone_number', models.CharField(max_length=13)),
                ('guide_number', models.CharField(max_length=30, unique=True)),
                ('zipcode', models.IntegerField(null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('state', models.BooleanField(default=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.country')),
                ('locality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.address_locality')),
                ('neighborhood', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.address_neighborhood')),
                ('process_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.enterprise_process_state')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.region')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.enterprise_service')),
                ('upz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.address_upz')),
            ],
        ),
        migrations.AddField(
            model_name='project_enterprise',
            name='form',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.form_enterprise'),
        ),
        migrations.CreateModel(
            name='Service_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField()),
                ('distance_api', models.CharField(max_length=300)),
                ('time_api', models.CharField(max_length=300)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now_add=True)),
                ('state', models.BooleanField(default=True)),
                ('final_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_address', to='api.service_location')),
                ('initial_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.service_location')),
                ('process_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.enterprise_process_state')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user_enterprise')),
            ],
        ),
        migrations.CreateModel(
            name='Service_Trazability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.IntegerField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('date_trace', models.DateField()),
                ('hour_trace', models.TimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('state', models.BooleanField(default=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.enterprise_processs')),
                ('process_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.enterprise_process_state')),
            ],
        ),
        migrations.CreateModel(
            name='Service_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_quantity', models.IntegerField()),
                ('total_distance', models.IntegerField()),
                ('optimal_capture', models.FileField(blank=True, null=True, upload_to=api.models.service_capture_directory_path)),
                ('initial_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.location_enterprise')),
                ('process_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.enterprise_process_state')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.enterprise_service')),
            ],
        ),
        migrations.AddField(
            model_name='enterprise_process_state',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.enterprise_processs'),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.country'),
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.region'),
        ),
        migrations.CreateModel(
            name='Address_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('state', models.BooleanField(default=True)),
                ('upz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.address_upz')),
            ],
        ),
        migrations.AddField(
            model_name='address_neighborhood',
            name='upz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.address_upz'),
        ),
        migrations.AddField(
            model_name='address_locality',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.city'),
        ),
        migrations.AddField(
            model_name='address_locality',
            name='subzone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subzone', to='api.address_zone'),
        ),
        migrations.AddField(
            model_name='address_locality',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.address_zone'),
        ),
        migrations.AlterField(
            model_name='location_enterprise',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.city'),
        ),
        migrations.AlterField(
            model_name='location_enterprise',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.country'),
        ),
    ]
