# Generated by Django 3.2.8 on 2022-01-28 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_auto_20220128_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address_neighborhood',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
