# Generated by Django 3.2.8 on 2022-01-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_address_neighborhood_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise_processs',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name='enterprise_processs',
            unique_together={('enterprise', 'name')},
        ),
    ]
