# Generated by Django 3.2.8 on 2022-02-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_auto_20220128_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_detail',
            name='description',
            field=models.CharField(default='Sin descripción', max_length=200),
        ),
        migrations.AddField(
            model_name='service_detail',
            name='initial_addres',
            field=models.CharField(default=3, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service_detail',
            name='name',
            field=models.CharField(default='Servicio de entrega', max_length=200),
        ),
    ]
