# Generated by Django 3.2.8 on 2022-02-01 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_auto_20220128_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise_service',
            name='route_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.route'),
        ),
        migrations.AddField(
            model_name='service_location',
            name='route_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.route'),
        ),
    ]
