# Generated by Django 3.2.8 on 2022-02-02 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_auto_20220201_0204'),
        ('api', '0042_auto_20220201_1000'),
    ]

    operations = [
    ]
