# Generated by Django 3.2.8 on 2022-02-02 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_merge_0042_auto_20220201_0204_0042_auto_20220201_1000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service_user',
            old_name='initial_address',
            new_name='service',
        ),
        migrations.RemoveField(
            model_name='service_user',
            name='final_address',
        ),
    ]
