# Generated by Django 3.2.8 on 2022-02-03 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_auto_20220202_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise_service',
            name='created_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.user_enterprise'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service_location',
            name='user_id_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='service_detail',
            name='total_distance',
            field=models.FloatField(),
        ),
    ]
