# Generated by Django 3.2.8 on 2022-02-03 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_auto_20220203_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_location',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.region'),
        ),
    ]
