# Generated by Django 3.2.8 on 2022-02-04 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_alter_service_location_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_location',
            name='guide_number_internal',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='service_location',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.project_enterprise'),
        ),
        migrations.AlterField(
            model_name='service_location',
            name='guide_number',
            field=models.CharField(max_length=30),
        ),
    ]
