# Generated by Django 3.2.8 on 2022-02-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_alter_service_location_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_trazability',
            name='description',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='service_trazability',
            name='group',
            field=models.IntegerField(default=1),
        ),
    ]
