# Generated by Django 3.2.8 on 2022-02-05 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_auto_20220204_1425'),
        ('api', '0047_auto_20220204_1449'),
    ]

    operations = [
    ]
