# Generated by Django 3.2.8 on 2022-02-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_merge_0047_auto_20220204_1425_0047_auto_20220204_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_trazability',
            name='date_trace',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='service_trazability',
            name='hour_trace',
            field=models.CharField(max_length=50),
        ),
    ]
