# Generated by Django 2.2.27 on 2022-02-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_auto_20220222_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_field',
            name='help',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
