# Generated by Django 3.2.8 on 2022-03-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_auto_20220227_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_detail',
            name='api_route',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
