# Generated by Django 3.2.8 on 2022-03-04 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_service_detail_api_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_location',
            name='answer_form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.answer_form'),
        ),
    ]
