# Generated by Django 3.2.8 on 2022-03-22 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_service_location_answer_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geo_Portal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('json_path', models.CharField(blank=True, max_length=300, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user_enterprise')),
                ('massive_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.massive_file')),
            ],
        ),
    ]
