# Generated by Django 3.2.8 on 2022-03-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_geo_portal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_field',
            name='help',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
