# Generated by Django 3.2.8 on 2022-03-23 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_geo_portal'),
    ]

    operations = [
        migrations.AddField(
            model_name='geo_portal',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='geo_portal',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
