# Generated by Django 3.2.8 on 2022-03-28 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_alter_form_field_help'),
        ('api', '0056_auto_20220323_1411'),
    ]

    operations = [
    ]
