# Generated by Django 3.2.8 on 2022-04-11 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_merge_20220328_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=40)),
                ('longitude', models.CharField(max_length=40)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('state', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user_enterprise')),
            ],
        ),
    ]
