# Generated by Django 3.2.8 on 2022-04-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_value_parameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_enterprise',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
