# Generated by Django 3.2.8 on 2022-05-13 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0060_alter_form_enterprise_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_enterprise',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user_enterprise',
            name='phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='user_enterprise',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='user_enterprise',
            unique_together={('enterprise', 'email')},
        ),
    ]
