# Generated by Django 3.2.8 on 2022-05-18 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_alter_form_enterprise_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='List_Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('position', models.IntegerField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('state', models.BooleanField(default=True)),
                ('field_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.field_type')),
                ('form_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.form_field')),
            ],
        ),
        migrations.CreateModel(
            name='Option_List_Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('state', models.BooleanField(default=True)),
                ('list_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.list_field')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.option')),
            ],
        ),
    ]
