# Generated by Django 3.2.8 on 2022-05-15 17:03

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_auto_20220513_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='camara_comercio',
            field=models.FileField(blank=True, null=True, upload_to=api.models.enterprise_directory_path),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='certificado_digital',
            field=models.FileField(blank=True, null=True, upload_to=api.models.enterprise_directory_path),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='confidencialidad',
            field=models.FileField(blank=True, null=True, upload_to=api.models.enterprise_directory_path),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='name',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='nit',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='rut',
            field=models.FileField(blank=True, null=True, upload_to=api.models.enterprise_directory_path),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='tratamiento_datos',
            field=models.FileField(blank=True, null=True, upload_to=api.models.enterprise_directory_path),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='website',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
