# Generated by Django 3.2.8 on 2022-05-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_form_field_row'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer_field',
            name='value',
            field=models.TextField(),
        ),
    ]
