# Generated by Django 3.2.8 on 2022-05-19 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_auto_20220515_1203'),
        ('api', '0062_form_field_row'),
    ]

    operations = [
    ]
