# Generated by Django 3.2.8 on 2022-05-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_merge_0062_auto_20220515_1203_0062_form_field_row'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='abreviation',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='login_page_state',
            field=models.BooleanField(default=False),
        ),
    ]
