# Generated by Django 3.2.8 on 2022-05-24 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_alter_answer_field_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='digital_field',
            name='list_field',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='digital_field',
            name='row_field',
            field=models.IntegerField(default=1),
        ),
    ]
