# Generated by Django 3.2.8 on 2022-05-23 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_auto_20220523_0942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enterprise',
            old_name='abreviation',
            new_name='acronym',
        ),
    ]
