# Generated by Django 3.2.8 on 2022-05-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_rename_abreviation_enterprise_acronym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='acronym',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='login_page_state',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
