# Generated by Django 3.2.8 on 2022-05-25 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_auto_20220524_1737'),
        ('api', '0066_auto_20220523_1035'),
    ]

    operations = [
    ]
