# Generated by Django 3.2.8 on 2022-06-02 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_merge_0064_auto_20220524_1737_0066_auto_20220523_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Api_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('state', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='api_usage',
            old_name='counter',
            new_name='limit',
        ),
        migrations.RemoveField(
            model_name='api_registry',
            name='column',
        ),
        migrations.RemoveField(
            model_name='api_usage',
            name='date',
        ),
        migrations.AddField(
            model_name='api_registry',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='api_usage',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='api_usage',
            name='enterprise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.enterprise'),
        ),
        migrations.AddField(
            model_name='api_usage',
            name='modify_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='api_registry',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='api_registry',
            name='value',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='api_registry',
            name='api',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.api_detail'),
        ),
        migrations.AlterField(
            model_name='api_usage',
            name='api',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.api_detail'),
        ),
        migrations.DeleteModel(
            name='Api_Enterprise',
        ),
    ]
