# Generated by Django 3.2.8 on 2022-06-05 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_merge_0064_auto_20220524_1737_0066_auto_20220523_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_enterprise',
            name='color',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='form_enterprise',
            name='theme',
            field=models.IntegerField(default=0),
        ),
    ]
