# Generated by Django 3.2.8 on 2022-06-02 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_auto_20220602_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='api_registry',
            name='enterprise',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.enterprise'),
            preserve_default=False,
        ),
    ]
