# Generated by Django 3.2.8 on 2022-06-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_api_registry_enterprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='api_usage',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
