# Generated by Django 3.2.8 on 2022-06-02 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_api_usage_state'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='api_usage',
            unique_together={('enterprise', 'api')},
        ),
    ]
