# Generated by Django 3.2.8 on 2022-06-06 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_alter_api_usage_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='api_registry',
            name='type_consume',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Api_Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.IntegerField()),
                ('used', models.IntegerField()),
                ('state', models.BooleanField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.api_detail')),
                ('enterprise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.enterprise')),
            ],
        ),
        migrations.AddField(
            model_name='api_registry',
            name='consume_pkg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.api_packages'),
        ),
    ]
