# Generated by Django 3.2.8 on 2022-06-06 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_auto_20220605_1817'),
        ('api', '0072_auto_20220606_1229'),
    ]

    operations = [
    ]
