# Generated by Django 3.2.8 on 2022-06-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_merge_0068_auto_20220605_1817_0072_auto_20220606_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_enterprise',
            name='token',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
