# Generated by Django 3.2.8 on 2022-06-13 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_user_enterprise_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('identification', models.BigIntegerField()),
                ('lookout_count', models.IntegerField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('state', models.BooleanField(default=True)),
                ('restrictive_lists', models.CharField(max_length=60000)),
                ('token_autorization', models.IntegerField()),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.enterprise')),
                ('type_identification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.type_identification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user_enterprise')),
            ],
        ),
    ]
