# Generated by Django 3.2.8 on 2022-06-15 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_signed_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form_Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_link', models.CharField(default='', max_length=100)),
                ('max_date', models.DateField(null=True)),
                ('date_state', models.BooleanField(default=True)),
                ('max_send', models.IntegerField(default=0)),
                ('send_state', models.BooleanField(default=True)),
                ('state', models.BooleanField(default=True)),
                ('form_enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.form_enterprise')),
            ],
        ),
    ]
