# Generated by Django 3.2.8 on 2022-06-15 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_signed_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signed_Document_Consecutive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_path', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('answer_consecutive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.answer_consecutive')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user_enterprise')),
            ],
        ),
    ]
