# Generated by Django 3.2.8 on 2022-06-15 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_form_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_link',
            name='modify_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
