# Generated by Django 3.2.8 on 2022-06-15 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_form_link_modify_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_link',
            name='date_state',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='form_link',
            name='send_state',
            field=models.BooleanField(default=False),
        ),
    ]
