# Generated by Django 3.2.8 on 2022-06-16 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_signed_document_consecutive'),
        ('api', '0079_auto_20220615_1712'),
    ]

    operations = [
    ]
