# Generated by Django 3.2.8 on 2022-06-17 20:05

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_merge_20220616_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_link',
            name='qr_path',
            field=models.FileField(blank=True, null=True, upload_to=api.models.qr_directory_path),
        ),
    ]
