# Generated by Django 3.2.8 on 2022-06-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_form_link_qr_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable_plataform',
            name='value',
            field=models.TextField(),
        ),
    ]
