# Generated by Django 3.2.8 on 2022-06-21 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_form_link_qr_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer_consecutive',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answer_form',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='answer_consecutive',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user_enterprise'),
        ),
        migrations.AlterField(
            model_name='answer_form',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user_enterprise'),
        ),
    ]
