# Generated by Django 3.2.8 on 2022-06-21 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_alter_variable_plataform_value'),
        ('api', '0082_auto_20220621_1515'),
    ]

    operations = [
    ]
