# Generated by Django 3.2.8 on 2022-06-22 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0083_merge_20220621_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_link',
            name='access',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='signed_document',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user_enterprise'),
        ),
        migrations.AlterField(
            model_name='signed_document_consecutive',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user_enterprise'),
        ),
    ]
