# Generated by Django 3.2.8 on 2022-06-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0084_auto_20220622_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='max_users',
            field=models.IntegerField(default=20),
        ),
    ]
