# Generated by Django 3.2.8 on 2022-06-30 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0085_enterprise_max_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile_document',
            name='restrictive_lists',
        ),
        migrations.AddField(
            model_name='profile_document',
            name='answer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.answer_field'),
        ),
        migrations.AddField(
            model_name='profile_document',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='profile_document',
            name='hash_info',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile_document',
            name='phone',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile_document',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
