# Generated by Django 3.2.8 on 2022-06-30 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0086_auto_20220630_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_document',
            name='qr_file',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
