# Generated by Django 3.2.8 on 2022-06-30 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0087_profile_document_qr_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_document',
            name='token_url',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
