# Generated by Django 3.2.8 on 2022-07-01 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_profile_document_token_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile_document',
            old_name='answer_id',
            new_name='answer',
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile_document',
            name='restrictive_lists',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='profile_document',
            name='qr_file',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.CreateModel(
            name='Sign_Profile_Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_url', models.TextField(default='')),
                ('hash_info', models.TextField(default='')),
                ('qr_file', models.CharField(max_length=200, null=True)),
                ('restrictive_lists', models.TextField(default='')),
                ('answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.answer_field')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profile')),
            ],
        ),
    ]
