# Generated by Django 3.2.8 on 2022-07-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0089_auto_20220701_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='role_enterprise',
            name='view_all',
            field=models.BooleanField(default=False),
        ),
    ]
