# Generated by Django 3.2.8 on 2022-07-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0089_auto_20220701_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign_profile_document',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
