# Generated by Django 3.2.8 on 2022-07-10 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0090_role_enterprise_view_all'),
        ('api', '0090_sign_profile_document_date'),
    ]

    operations = [
    ]
