# Generated by Django 3.2.8 on 2022-07-12 15:17

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0091_merge_20220710_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_enterprise',
            name='logo_path',
            field=models.FileField(blank=True, null=True, upload_to=api.models.form_directory_path),
        ),
    ]
