# Generated by Django 3.2.8 on 2022-07-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0092_form_enterprise_logo_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field_type',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
