# Generated by Django 3.2.8 on 2022-07-20 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0092_form_enterprise_logo_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_document',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user_enterprise'),
        ),
    ]
