# Generated by Django 3.2.8 on 2022-07-20 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0093_alter_field_type_name'),
        ('api', '0093_alter_profile_document_user'),
    ]

    operations = [
    ]
