# Generated by Django 3.2.8 on 2022-07-21 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0094_merge_20220719_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traceability_user',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user_enterprise'),
        ),
    ]
