# Generated by Django 3.2.8 on 2022-07-28 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0095_alter_traceability_user_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traceability_user',
            name='description',
            field=models.TextField(),
        ),
    ]
