# Generated by Django 3.2.8 on 2022-08-23 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0096_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_enterprise',
            name='pin',
            field=models.CharField(default='', max_length=10),
        ),
    ]
