# Generated by Django 3.2.8 on 2022-08-24 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0096_alter_traceability_user_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device_Info_Movil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('serial', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=100)),
                ('battery', models.IntegerField()),
                ('gps', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user_enterprise')),
            ],
        ),
    ]
