# Generated by Django 3.2.8 on 2022-08-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0097_device_info_movil'),
    ]

    operations = [
        migrations.AddField(
            model_name='device_info_movil',
            name='version_app',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
