# Generated by Django 3.2.8 on 2022-08-29 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0097_form_enterprise_pin'),
        ('api', '0098_device_info_movil_version_app'),
    ]

    operations = [
    ]
