# Generated by Django 3.2.8 on 2022-09-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0099_merge_20220829_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traceability_user',
            name='element',
            field=models.CharField(max_length=100),
        ),
    ]
