# Generated by Django 3.2.8 on 2022-09-05 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0100_alter_traceability_user_element'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign_profile_document',
            name='token_registry',
            field=models.TextField(default=''),
        ),
    ]
