# Generated by Django 3.2.8 on 2022-09-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0101_sign_profile_document_token_registry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='value',
            field=models.CharField(max_length=35),
        ),
    ]
