# Generated by Django 3.2.8 on 2022-09-19 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0102_alter_option_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='role_enterprise',
            name='time_zone',
            field=models.CharField(default='08:00*%*18:00', max_length=100),
        ),
    ]
