# Generated by Django 3.2.8 on 2022-09-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0103_role_enterprise_time_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='device_info_movil',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
