# Generated by Django 3.2.8 on 2022-09-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0103_role_enterprise_time_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_enterprise',
            name='register_state',
            field=models.BooleanField(default=True),
        ),
    ]
