# Generated by Django 3.2.8 on 2022-09-25 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0104_device_info_movil_last_update'),
        ('api', '0104_user_enterprise_register_state'),
    ]

    operations = [
    ]
