# Generated by Django 3.2.8 on 2022-09-25 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0105_merge_20220925_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_enterprise',
            name='register_admin',
            field=models.BooleanField(default=True),
        ),
    ]
