# Generated by Django 3.2.8 on 2022-09-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0106_user_enterprise_register_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='device_info_movil',
            name='last_conection',
            field=models.DateTimeField(default="2022-09-21 15:27:36.986"),
            preserve_default=False,
        ),
    ]
