# Generated by Django 3.2.8 on 2022-10-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0107_device_info_movil_last_conection'),
    ]

    operations = [
        migrations.AddField(
            model_name='digital_field',
            name='line_height',
            field=models.CharField(default='', max_length=5),
        ),
    ]
