# Generated by Django 3.2.8 on 2022-10-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0108_document_identification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document_identification',
            name='data_form',
            field=models.CharField(max_length=60000),
        ),
    ]
