# Generated by Django 3.2.8 on 2022-10-04 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0109_alter_document_identification_data_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='document_identification',
            name='form_field',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.form_field'),
            preserve_default=False,
        ),
    ]
