# Generated by Django 3.2.8 on 2022-10-05 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0108_digital_field_line_height'),
        ('api', '0110_document_identification_form_field'),
    ]

    operations = [
    ]
