# Generated by Django 3.2.8 on 2022-10-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0111_merge_20221004_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='value',
            field=models.CharField(max_length=40),
        ),
    ]
