# Generated by Django 3.2.8 on 2022-10-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0113_auto_20221023_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer_consecutive',
            name='serial_number',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='answer_form',
            name='serial_number',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='serial',
            field=models.CharField(max_length=3, null=True, unique=True),
        ),
    ]
