# Generated by Django 3.2.8 on 2022-10-26 17:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0114_auto_20221026_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serial_Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=1)),
                ('count', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999999)])),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.enterprise')),
            ],
        ),
        migrations.AlterField(
            model_name='answer_consecutive',
            name='serial_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.serial_number'),
        ),
        migrations.AlterField(
            model_name='answer_form',
            name='serial_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.serial_number'),
        ),
    ]
