# Generated by Django 3.2.8 on 2022-10-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0115_auto_20221026_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='serial',
            field=models.CharField(max_length=4, null=True, unique=True),
        ),
    ]
