# Generated by Django 3.2.8 on 2022-10-26 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0116_alter_enterprise_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_field_parameter',
            name='value',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='serial_number',
            name='count',
            field=models.IntegerField(),
        ),
    ]
