# Generated by Django 3.2.8 on 2022-11-10 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0117_auto_20221026_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer_form',
            name='form_version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='form_enterprise',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Form_Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=1)),
                ('json_data', models.TextField()),
                ('form_enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.form_enterprise')),
            ],
        ),
    ]
