# Generated by Django 3.2.8 on 2022-11-11 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0118_auto_20221110_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer_consecutive',
            name='form_version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='form_consecutive',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Form_Consecutive_Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=1)),
                ('json_data', models.TextField()),
                ('form_consecutive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.form_consecutive')),
            ],
        ),
    ]
