# Generated by Django 3.2.8 on 2022-11-24 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0119_auto_20221111_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='api_key',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
