# Generated by Django 3.2.8 on 2022-11-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0120_follow_user_offline'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification_user',
            name='extra',
            field=models.TextField(null=True),
        ),
    ]
