# Generated by Django 3.2.8 on 2022-11-24 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0121_notification_user_extra'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Form_Consecutive_Version',
        ),
    ]
