# Generated by Django 3.2.8 on 2022-11-24 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0121_notification_user_extra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='system_log',
            old_name='response_code',
            new_name='type',
        ),
        migrations.AddField(
            model_name='system_log',
            name='source',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='system_log',
            name='action',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='system_log',
            name='data',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='system_log',
            name='response_data',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='system_log',
            name='url',
            field=models.TextField(),
        ),
    ]
