# Generated by Django 3.2.8 on 2022-11-25 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0122_auto_20221124_1819'),
        ('api', '0122_delete_form_consecutive_version'),
    ]

    operations = [
    ]
