# Generated by Django 3.2.8 on 2022-11-25 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0120_enterprise_api_key'),
        ('api', '0123_merge_20221124_2005'),
    ]

    operations = [
    ]
