# Generated by Django 3.2.8 on 2022-12-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0124_merge_20221125_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer_form',
            name='doc_hash',
            field=models.TextField(default=None, null=True),
        ),
    ]
