# Generated by Django 3.2.8 on 2022-12-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0125_answer_form_doc_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer_consecutive',
            name='doc_hash',
            field=models.TextField(default=None, null=True),
        ),
    ]
