# Generated by Django 3.2.8 on 2022-12-15 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0126_answer_consecutive_doc_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sign_OTP_Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('token_url', models.TextField(default='')),
                ('hash_info', models.TextField(default='')),
                ('qr_file', models.CharField(max_length=200, null=True)),
                ('token_registry', models.TextField(default='')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.answer_field')),
            ],
        ),
    ]
