# Generated by Django 3.2.8 on 2022-12-14 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0126_answer_consecutive_doc_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='traceability_user',
            name='extra',
            field=models.TextField(null=True),
        ),
    ]
