# Generated by Django 3.2.8 on 2022-12-15 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0127_sign_otp_document'),
        ('api', '0127_traceability_user_extra'),
    ]

    operations = [
    ]
