# Generated by Django 3.2.8 on 2022-12-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0128_merge_20221215_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='permit_enterprise',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
