# Generated by Django 3.2.8 on 2023-02-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0129_permit_enterprise_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='public_color',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
