# Generated by Django 3.2.8 on 2023-01-20 21:11

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0129_permit_enterprise_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Env_Form_Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('help', models.CharField(max_length=5000, null=True)),
                ('obligatory', models.BooleanField(default=True)),
                ('row', models.IntegerField(default=0)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('state', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Envelope_Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=100)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('state', models.BooleanField(default=True)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.enterprise')),
            ],
        ),
        migrations.CreateModel(
            name='Envelope_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_user', models.IntegerField(default=1)),
                ('user', models.IntegerField()),
                ('position', models.IntegerField(default=1)),
                ('color', models.CharField(max_length=7)),
                ('state', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Envelope_Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=1)),
                ('flow_type', models.IntegerField(default=1)),
                ('order_important', models.BooleanField(default=False)),
                ('autosave', models.BooleanField(default=False)),
                ('message_type', models.IntegerField(default=1)),
                ('subject', models.CharField(max_length=100, null=True)),
                ('content', models.TextField(null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(default=0)),
                ('state', models.BooleanField(default=True)),
                ('envelope_enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.envelope_enterprise')),
            ],
        ),
        migrations.CreateModel(
            name='Message_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('state', models.BooleanField(default=True)),
                ('envelope_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.envelope_user')),
            ],
        ),
        migrations.CreateModel(
            name='Field_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('env_form_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.env_form_field')),
                ('envelope_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.envelope_user')),
            ],
        ),
        migrations.CreateModel(
            name='External_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=100)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.enterprise')),
            ],
        ),
        migrations.CreateModel(
            name='Envelope_Version_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('template', models.FileField(blank=True, null=True, upload_to=api.models.env_version_template_path)),
                ('position', models.IntegerField(default=1)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('state', models.BooleanField(default=True)),
                ('envelope_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.envelope_version')),
            ],
        ),
        migrations.AddField(
            model_name='envelope_user',
            name='envelope_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.envelope_version'),
        ),
        migrations.CreateModel(
            name='Env_Option_Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('state', models.BooleanField(default=True)),
                ('env_form_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.env_form_field')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.option')),
            ],
        ),
        migrations.CreateModel(
            name='Env_Form_Field_Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=1000)),
                ('state', models.BooleanField(default=True)),
                ('env_form_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.env_form_field')),
                ('parameter_validate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.parameter_validate')),
            ],
        ),
        migrations.AddField(
            model_name='env_form_field',
            name='envelope_version_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.envelope_version_form'),
        ),
        migrations.AddField(
            model_name='env_form_field',
            name='field_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.field_type'),
        ),
        migrations.CreateModel(
            name='Env_Field_Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('extra', models.CharField(max_length=20)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('state', models.BooleanField(default=True)),
                ('field_father', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.env_form_field')),
                ('field_son', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_son', to='api.env_form_field')),
            ],
        ),
        migrations.CreateModel(
            name='Env_Digital_Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.IntegerField()),
                ('left', models.CharField(max_length=20)),
                ('top', models.CharField(max_length=20)),
                ('font', models.CharField(max_length=15)),
                ('size', models.IntegerField()),
                ('color', models.CharField(max_length=7)),
                ('bold', models.BooleanField(default=False)),
                ('italic', models.BooleanField(default=False)),
                ('underline', models.BooleanField(default=False)),
                ('width', models.CharField(max_length=5)),
                ('height', models.CharField(max_length=5)),
                ('line_height', models.CharField(default='', max_length=5)),
                ('option', models.IntegerField(default=0)),
                ('option_value', models.IntegerField(null=True)),
                ('row_field', models.IntegerField(default=1)),
                ('list_field', models.IntegerField(null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('state', models.BooleanField(default=True)),
                ('env_form_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.env_form_field')),
            ],
        ),
    ]
