# Generated by Django 3.2.8 on 2023-02-16 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0130_enterprise_public_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='public_color_Text',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
