# Generated by Django 3.2.8 on 2023-01-23 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0130_auto_20230120_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='envelope_enterprise',
            name='pin',
            field=models.CharField(default='', max_length=10),
        ),
    ]
