# Generated by Django 3.2.8 on 2023-01-25 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0131_envelope_enterprise_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='external_user',
            name='phone_ind',
            field=models.CharField(default='57', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='external_user',
            unique_together={('email', 'enterprise')},
        ),
    ]
