# Generated by Django 2.2.10 on 2023-02-27 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0131_enterprise_public_color_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_field',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='Field_Condition',
            name='extra',
            field=models.CharField(max_length=50),
        ),
    ]
