# Generated by Django 3.2.8 on 2023-01-26 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0132_auto_20230125_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer_Envelope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('doc_hash', models.TextField(default=None, null=True)),
                ('state', models.BooleanField(default=True)),
                ('envelope_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.envelope_version')),
                ('serial_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.serial_number')),
            ],
        ),
        migrations.CreateModel(
            name='Env_List_Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('position', models.IntegerField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('state', models.BooleanField(default=True)),
                ('env_form_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.env_form_field')),
                ('field_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.field_type')),
            ],
        ),
        migrations.CreateModel(
            name='Env_Option_List_Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('state', models.BooleanField(default=True)),
                ('env_list_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.env_list_field')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.option')),
            ],
        ),
        migrations.CreateModel(
            name='Answer_Envelope_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.IntegerField()),
                ('online', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('longitude', models.FloatField(null=True)),
                ('latitude', models.FloatField(null=True)),
                ('state', models.BooleanField(default=True)),
                ('answer_envelope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.answer_envelope')),
                ('envelope_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.envelope_user')),
                ('user_rol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user_enterprise')),
            ],
        ),
        migrations.CreateModel(
            name='Answer_Envelope_Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('state', models.BooleanField(default=True)),
                ('answer_envelope_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.answer_envelope_user')),
                ('field_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.field_user')),
            ],
        ),
    ]
