# Generated by Django 3.2.8 on 2023-01-30 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0133_answer_envelope_answer_envelope_field_answer_envelope_user_env_list_field_env_option_list_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='envelope_version',
            name='sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='envelope_version',
            name='ws',
            field=models.BooleanField(default=False),
        ),
    ]
