# Generated by Django 3.2.8 on 2023-02-13 23:43

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0134_auto_20230130_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('valor', models.IntegerField()),
                ('image', models.FileField(blank=True, null=True, upload_to=api.models.profile_directory_path)),
                ('items', models.CharField(blank=True, max_length=500)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('state', models.BooleanField(default=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user_enterprise')),
            ],
        ),
        migrations.CreateModel(
            name='Enterprise_Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_date', models.DateTimeField()),
                ('finish_date', models.DateTimeField()),
                ('state', models.BooleanField(default=True)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.enterprise')),
            ],
        ),
    ]
