# Generated by Django 3.2.8 on 2023-02-14 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0135_enterprise_plans_plans'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=500)),
                ('cant', models.IntegerField()),
                ('service', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='History_Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_pay', models.IntegerField()),
                ('valor', models.IntegerField()),
                ('buy_date', models.DateTimeField()),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.enterprise')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.plans')),
            ],
        ),
    ]
