# Generated by Django 3.2.8 on 2023-02-14 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0136_history_plans_service_plans'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plans',
            old_name='valor',
            new_name='price',
        ),
    ]
