# Generated by Django 3.2.8 on 2023-02-14 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0137_rename_valor_plans_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plans',
            old_name='user_id',
            new_name='user',
        ),
    ]
