# Generated by Django 3.2.8 on 2023-02-14 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0138_rename_user_id_plans_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history_plans',
            old_name='valor',
            new_name='price',
        ),
    ]
