# Generated by Django 3.2.8 on 2023-02-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0139_rename_valor_history_plans_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='user',
            field=models.IntegerField(),
        ),
    ]
