# Generated by Django 3.2.8 on 2023-02-14 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0140_alter_plans_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user_enterprise'),
        ),
    ]
