# Generated by Django 3.2.8 on 2023-02-15 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0142_remove_plans_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plans',
            name='items',
        ),
        migrations.CreateModel(
            name='Items_Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.plans')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.service_plans')),
            ],
        ),
    ]
