# Generated by Django 3.2.8 on 2023-02-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0143_auto_20230215_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='items_plans',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='service_plans',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
