# Generated by Django 3.2.8 on 2023-02-15 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0144_auto_20230215_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='color',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
