# Generated by Django 3.2.8 on 2023-02-16 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0130_enterprise_public_color'),
        ('api', '0145_plans_color'),
    ]

    operations = [
    ]
