# Generated by Django 3.2.8 on 2023-02-16 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0131_enterprise_public_color_text'),
        ('api', '0146_merge_0130_enterprise_public_color_0145_plans_color'),
    ]

    operations = [
    ]
