# Generated by Django 3.2.8 on 2023-02-16 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0147_merge_20230216_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500)),
                ('image_name', models.CharField(blank=True, max_length=500)),
                ('path', models.CharField(blank=True, max_length=500)),
                ('cant', models.IntegerField()),
                ('state', models.BooleanField(default=True)),
            ],
        ),
    ]
