# Generated by Django 3.2.8 on 2023-02-16 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0148_home_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home_items',
            name='cant',
        ),
    ]
