# Generated by Django 3.2.8 on 2023-02-16 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0149_remove_home_items_cant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home_Items_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant', models.IntegerField()),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.enterprise')),
                ('home_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.home_items')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user_enterprise')),
            ],
        ),
    ]
