# Generated by Django 3.2.8 on 2023-02-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0151_remove_home_items_user_enterprise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='price',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
