# Generated by Django 3.2.8 on 2023-03-07 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0154_alter_task_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='subproject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.subproject'),
            preserve_default=False,
        ),
    ]
