# Generated by Django 3.2.8 on 2023-03-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0155_task_subproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='observation',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
