# Generated by Django 3.2.8 on 2023-03-07 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0156_task_observation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='observation',
        ),
    ]
