# Generated by Django 3.2.8 on 2023-03-07 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0157_remove_task_observation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.enterprise_process_state'),
        ),
    ]
