# Generated by Django 2.2.10 on 2023-03-07 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0132_auto_20230227_1703'),
        ('api', '0158_alter_task_state'),
    ]

    operations = [
    ]
