# Generated by Django 2.2.10 on 2023-03-16 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0159_merge_20230307_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programming_Visits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('state', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subproject_Parameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_enabled', models.CharField(blank=True, max_length=500)),
                ('start_time_enabled', models.CharField(blank=True, max_length=500)),
                ('end_time_enabled', models.CharField(blank=True, max_length=500)),
                ('travel_time', models.CharField(blank=True, max_length=500)),
                ('lunch_time_state', models.BooleanField(default=False)),
                ('lunch_time', models.CharField(blank=True, max_length=500)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('subproject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Subproject')),
            ],
        ),
        migrations.CreateModel(
            name='Programming_Visits_Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programming_visits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Programming_Visits')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Task')),
            ],
        ),
    ]
