# Generated by Django 2.2.10 on 2023-03-20 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0160_auto_20230316_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='programming_visits',
            name='subproject',
            field=models.ForeignKey(default=30, on_delete=django.db.models.deletion.CASCADE, to='api.Subproject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programming_visits',
            name='user',
            field=models.ForeignKey(default='30', on_delete=django.db.models.deletion.CASCADE, to='api.User_Enterprise'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='duration',
            field=models.CharField(default='30', max_length=10),
        ),
    ]
