# Generated by Django 2.2.10 on 2023-03-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0161_auto_20230320_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproject',
            name='main_form',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
