# Generated by Django 2.2.10 on 2023-03-20 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0162_auto_20230320_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form_Answer_Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('Answer_Form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Answer_Form')),
                ('subproject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Subproject')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Task')),
            ],
        ),
    ]
