# Generated by Django 2.2.10 on 2023-03-20 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0163_auto_20230320_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='visit_form',
            field=models.IntegerField(null=True),
        ),
    ]
