# Generated by Django 3.2.8 on 2023-04-26 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0164_auto_20230320_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field_condition',
            name='extra',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='form_answer_task',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='programming_visits',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='programming_visits_task',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='subproject_parameters',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='task',
            name='duration',
            field=models.CharField(default=30, max_length=10),
        ),
        migrations.CreateModel(
            name='Logs_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_form', models.CharField(blank=True, max_length=40)),
                ('latitude', models.CharField(blank=True, max_length=500)),
                ('longitude', models.CharField(blank=True, max_length=500)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('date', models.CharField(blank=True, max_length=500)),
                ('hour', models.CharField(blank=True, max_length=500)),
                ('platform', models.CharField(blank=True, max_length=40)),
                ('state', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user_enterprise')),
            ],
        ),
    ]
