# Generated by Django 3.2.8 on 2023-04-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0165_auto_20230426_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs_form',
            name='platform',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='logs_form',
            name='state',
            field=models.IntegerField(),
        ),
    ]
