# Generated by Django 3.2.8 on 2023-05-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0166_auto_20230426_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massive_errors',
            name='data',
            field=models.TextField(),
        ),
    ]
