# Generated by Django 3.2.8 on 2023-05-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0166_auto_20230426_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer_form',
            name='time_stamp',
            field=models.DateTimeField(null=True),
        ),
    ]
