# Generated by Django 3.2.8 on 2023-05-17 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0167_alter_massive_errors_data'),
        ('api', '0167_answer_form_time_stamp'),
    ]

    operations = [
    ]
