# Generated by Django 3.2.8 on 2023-05-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0167_answer_form_time_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='device_info_movil',
            name='permission_location',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
