# Generated by Django 3.2.8 on 2023-05-19 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0168_device_info_movil_permission_location'),
        ('api', '0168_merge_20230517_1100'),
    ]

    operations = [
    ]
