# Generated by Django 3.2.8 on 2023-05-19 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0169_merge_20230519_1108'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='permit',
            unique_together=set(),
        ),
    ]
