# Generated by Django 3.2.8 on 2023-05-26 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0170_alter_permit_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='token_link',
            field=models.CharField(default='', max_length=100),
        ),
    ]
