# Generated by Django 3.2.8 on 2023-05-26 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0170_alter_permit_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise_Email_Conf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.TextField()),
                ('port', models.IntegerField(default=587)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('use_tls', models.BooleanField(default=True)),
                ('state', models.BooleanField(default=True)),
                ('enterprise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.enterprise')),
            ],
        ),
    ]
