# Generated by Django 3.2.8 on 2023-05-26 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0171_enterprise_email_conf'),
        ('api', '0171_enterprise_token_link'),
    ]

    operations = [
    ]
