# Generated by Django 3.2.8 on 2023-06-22 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0172_merge_20230526_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer_form',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
