# Generated by Django 3.2.8 on 2023-06-20 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0172_merge_20230526_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_link',
            name='shared_media',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='form_link',
            name='shared_to',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
