# Generated by Django 3.2.8 on 2023-06-21 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0173_auto_20230619_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_link',
            name='process_state',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, to='api.enterprise_process_state'),
        ),
    ]
