# Generated by Django 3.2.8 on 2023-06-22 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0173_alter_answer_form_time_stamp'),
        ('api', '0174_form_link_process_state'),
    ]

    operations = [
    ]
