# Generated by Django 3.2.8 on 2023-06-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0175_merge_20230622_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='serial_number',
            field=models.CharField(default='NA', max_length=40),
        ),
    ]
