# Generated by Django 3.2.8 on 2023-06-26 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0176_task_serial_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit_Task_Answer_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('answer_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.answer_form')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.task')),
            ],
        ),
    ]
