# Generated by Django 3.2.8 on 2023-06-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0177_visit_task_answer_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_field',
            name='obligatory_visit',
            field=models.BooleanField(default=False),
        ),
    ]
