# Generated by Django 3.2.8 on 2023-06-28 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0178_form_field_obligatory_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='answer_form_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
