# Generated by Django 3.2.8 on 2023-06-29 20:37

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0179_task_answer_form_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Massive_Zip_Pdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filters', models.TextField()),
                ('template_folder', models.TextField(null=True)),
                ('template_zip', models.FileField(blank=True, null=True, upload_to=api.models.template_directory_zip_path)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('success', models.IntegerField(default=0)),
                ('error', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('state', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user_enterprise')),
            ],
        ),
        migrations.CreateModel(
            name='Zip_Errors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.IntegerField()),
                ('data', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('massive_zip_pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.massive_zip_pdf')),
            ],
        ),
    ]
