# Generated by Django 3.2.8 on 2023-07-03 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0180_massive_zip_pdf_zip_errors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sign_Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('creation_date', models.DateTimeField()),
                ('answer_field', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.answer_field')),
            ],
        ),
    ]
