# Generated by Django 3.2.8 on 2023-07-03 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0181_sign_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sign_email',
            name='creation_date',
        ),
    ]
