# Generated by Django 3.2.8 on 2023-07-03 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0182_remove_sign_email_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign_email',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default='2023-07-01 00:00:00.862773-05'),
            preserve_default=False,
        ),
    ]
