# Generated by Django 3.2.8 on 2023-07-06 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0183_sign_email_creation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document_Without_Sing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_path', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('answer_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.answer_form')),
            ],
        ),
    ]
