# Generated by Django 3.2.8 on 2023-07-12 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0184_document_without_sing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer_Envelope_Verified',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.BigIntegerField(null=True)),
                ('token_link', models.CharField(default='', max_length=100)),
                ('checker_td', models.BooleanField(null=True)),
                ('checker_hd', models.BooleanField(null=True)),
                ('verified', models.BooleanField(null=True)),
                ('comment', models.TextField()),
                ('verified_date', models.DateTimeField(null=True)),
                ('checker_date', models.DateTimeField(null=True)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Envelope_User_Verified',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_check', models.IntegerField(default=1)),
                ('send_time', models.DateTimeField(null=True)),
                ('state', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='envelope_enterprise',
            name='enterprise',
        ),
        migrations.RemoveField(
            model_name='envelope_user',
            name='type_user',
        ),
        migrations.RemoveField(
            model_name='envelope_user',
            name='user',
        ),
        migrations.AddField(
            model_name='answer_envelope',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='answer_envelope',
            name='token_link',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='answer_envelope_user',
            name='approver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answer_envelope_user',
            name='limit_time',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='answer_envelope_user',
            name='notification_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='answer_envelope_user',
            name='token_link',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='answer_envelope_user',
            name='type_user',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='answer_envelope_user',
            name='user',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='env_digital_field',
            name='envelope_version_form_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='envelope_enterprise',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user_enterprise'),
        ),
        migrations.AddField(
            model_name='envelope_version',
            name='checker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='envelope_version',
            name='limit_alert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='envelope_version',
            name='limit_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='envelope_version',
            name='limit_time',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='envelope_version',
            name='respect_participant',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='answer_envelope_field',
            name='answer_envelope_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.answer_envelope_user'),
        ),
        migrations.AlterField(
            model_name='answer_envelope_user',
            name='state',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Field_Verified',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('response', models.TextField()),
                ('answer_verified', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.answer_envelope_verified')),
                ('envelope_user_verified', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.envelope_user_verified')),
            ],
        ),
        migrations.AddField(
            model_name='envelope_user_verified',
            name='answer_envelope_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.answer_envelope_user'),
        ),
        migrations.AddField(
            model_name='answer_envelope_verified',
            name='answer_envelope_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.answer_envelope_user'),
        ),
        migrations.AddField(
            model_name='answer_envelope_verified',
            name='type_identification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.type_identification'),
        ),
        migrations.CreateModel(
            name='Answer_Envelope_Checker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_link', models.CharField(default='', max_length=100)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('state', models.BooleanField(default=False)),
                ('answer_envelope_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.answer_envelope_user')),
            ],
        ),
        migrations.CreateModel(
            name='Answer_Envelope_Approve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_link', models.CharField(default='', max_length=100)),
                ('approve', models.BooleanField(null=True)),
                ('comment', models.TextField()),
                ('approve_date', models.DateTimeField(null=True)),
                ('answer_envelope_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.answer_envelope_user')),
            ],
        ),
    ]
