# Generated by Django 3.2.8 on 2023-07-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0185_auto_20230712_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer_envelope_checker',
            name='token',
            field=models.IntegerField(default=0),
        ),
    ]
