# Generated by Django 3.2.8 on 2023-07-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0186_answer_envelope_checker_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_enterprise',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
