# Generated by Django 3.2.8 on 2023-08-02 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0187_alter_user_enterprise_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='History_Create_Share_Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('token', models.IntegerField(default=0)),
                ('Share', models.CharField(max_length=100)),
                ('id_form', models.CharField(blank=True, max_length=40)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.enterprise')),
            ],
        ),
    ]
