# Generated by Django 3.2.8 on 2023-08-02 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0188_history_create_share_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history_create_share_documents',
            name='Share',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='history_create_share_documents',
            name='token',
            field=models.CharField(max_length=100),
        ),
    ]
