# Generated by Django 3.2.8 on 2023-08-03 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0189_auto_20230802_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_link',
            name='general',
            field=models.BooleanField(default=True),
        ),
    ]
