# Generated by Django 3.2.8 on 2023-08-03 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0190_form_link_general'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form_link',
            old_name='general',
            new_name='general_share',
        ),
    ]
