# Generated by Django 3.2.8 on 2023-08-03 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0191_rename_general_form_link_general_share'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form_link',
            old_name='general_share',
            new_name='general_shared',
        ),
    ]
