# Generated by Django 3.2.8 on 2023-08-16 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0192_rename_general_share_form_link_general_shared'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='public_color_text_title',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
