# Generated by Django 3.2.8 on 2023-08-15 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0192_rename_general_share_form_link_general_shared'),
    ]

    operations = [
        migrations.CreateModel(
            name='Validate_Answer_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.BooleanField(default=False)),
                ('cause', models.IntegerField(default=0)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('answer_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.answer_form')),
            ],
        ),
    ]
