# Generated by Django 3.2.8 on 2023-08-17 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0193_enterprise_public_color_text_title'),
        ('api', '0193_validate_answer_form'),
    ]

    operations = [
    ]
