# Generated by Django 3.2.8 on 2023-08-20 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0194_merge_20230817_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='public_color_header_title',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
