# Generated by Django 3.2.8 on 2023-08-21 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0195_enterprise_public_color_header_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='public_color_footer',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='public_color_footer_title',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
