# Generated by Django 3.2.8 on 2023-08-25 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0196_auto_20230820_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Landing_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('corporate', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('phone', models.BigIntegerField()),
                ('city', models.CharField(max_length=60)),
                ('ip_address', models.CharField(max_length=20)),
                ('terms', models.BooleanField(default=False)),
                ('newslet', models.BooleanField(default=False)),
            ],
        ),
    ]
