# Generated by Django 3.2.8 on 2023-08-31 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0197_landing_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproject',
            name='email',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
