# Generated by Django 3.2.8 on 2023-09-01 19:25

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0197_landing_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer_envelope_verified',
            name='identification_back',
            field=models.FileField(blank=True, null=True, upload_to=api.models.env_doc_verified_path),
        ),
        migrations.AddField(
            model_name='answer_envelope_verified',
            name='identification_front',
            field=models.FileField(blank=True, null=True, upload_to=api.models.env_doc_verified_path),
        ),
    ]
