# Generated by Django 3.2.8 on 2023-09-04 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0198_subproject_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ani_Lyn_Melmac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(max_length=20, null=True)),
                ('first_last_name', models.CharField(max_length=20)),
                ('second_last_name', models.CharField(max_length=20, null=True)),
                ('identification', models.BigIntegerField()),
                ('live', models.CharField(max_length=20, null=True)),
                ('expedition_date', models.DateField(null=True)),
                ('data_form', models.CharField(max_length=60000)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('type_identification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.type_identification')),
            ],
        ),
    ]
