# Generated by Django 3.2.8 on 2023-09-05 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0199_ani_lyn_melmac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ani_lyn_melmac',
            name='expedition_date',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
