# Generated by Django 3.2.8 on 2023-09-06 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0198_auto_20230901_1425'),
        ('api', '0200_alter_ani_lyn_melmac_expedition_date'),
    ]

    operations = [
    ]
