# Generated by Django 3.2.8 on 2023-09-15 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0201_merge_20230905_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='external_user',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='external_user',
            name='phone_ind',
            field=models.CharField(default='+57', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='external_user',
            unique_together={('email', 'phone', 'enterprise')},
        ),
    ]
