# Generated by Django 3.2.8 on 2023-10-09 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0202_auto_20230915_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer_envelope_user',
            name='limit_public',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='external_user',
            name='phone_ind',
            field=models.CharField(default='+57-co', max_length=10),
        ),
        migrations.CreateModel(
            name='Answer_Envelope_Extend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_envelope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.answer_envelope')),
                ('answer_envelope_child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_envelope_extend_extend', to='api.answer_envelope')),
            ],
        ),
    ]
