# Generated by Django 3.2.8 on 2023-10-10 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0202_auto_20230915_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='external_user',
            name='phone_ind',
            field=models.CharField(default='+57-co', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='external_user',
            unique_together={('email', 'phone_ind', 'phone', 'enterprise')},
        ),
        migrations.CreateModel(
            name='Form_Temporal_Digital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temporal', models.CharField(max_length=1000)),
                ('id_form', models.CharField(blank=True, max_length=40)),
                ('token', models.CharField(blank=True, max_length=70)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user_enterprise')),
            ],
        ),
    ]
