# Generated by Django 3.2.8 on 2023-10-09 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0203_auto_20231009_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer_envelope_extend',
            name='external_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.external_user'),
        ),
    ]
