# Generated by Django 3.2.8 on 2023-10-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0203_auto_20231009_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_temporal_digital',
            name='temporal',
            field=models.CharField(max_length=60000),
        ),
    ]
