# Generated by Django 3.2.8 on 2023-10-17 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0206_alter_form_temporal_digital_temporal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Element_Type_Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('state', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Env_Digital_Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=5000, null=True)),
                ('url_src', models.CharField(max_length=5000, null=True)),
                ('page', models.IntegerField()),
                ('left', models.CharField(max_length=20)),
                ('top', models.CharField(max_length=20)),
                ('font', models.CharField(max_length=15)),
                ('size', models.IntegerField()),
                ('color', models.CharField(max_length=7)),
                ('justify', models.CharField(max_length=15)),
                ('bold', models.BooleanField(default=False)),
                ('italic', models.BooleanField(default=False)),
                ('underline', models.BooleanField(default=False)),
                ('width', models.CharField(max_length=5)),
                ('height', models.CharField(max_length=5)),
                ('line_height', models.CharField(default='', max_length=5)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('state', models.BooleanField(default=True)),
                ('element_type_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.element_type_config')),
                ('envelope_version_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.envelope_version_form')),
            ],
        ),
    ]
