# Generated by Django 3.2.8 on 2023-10-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0206_alter_form_temporal_digital_temporal'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise_email_conf',
            name='authenticate_domain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enterprise_email_conf',
            name='brand_link',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enterprise_email_conf',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default='2023-10-18T21:30:14.654Z'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enterprise_email_conf',
            name='dns',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='enterprise_email_conf',
            name='domain',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='enterprise_email_conf',
            name='email_config',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='enterprise_email_conf',
            name='verify_sender',
            field=models.BooleanField(default=False),
        ),
    ]
