# Generated by Django 3.2.8 on 2023-10-18 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0204_answer_envelope_extend_external_user'),
        ('api', '0206_alter_form_temporal_digital_temporal'),
    ]

    operations = [
    ]
