# Generated by Django 3.2.8 on 2023-10-24 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0207_element_type_config_env_digital_element'),
        ('api', '0207_merge_20231018_1507'),
    ]

    operations = [
    ]
