# Generated by Django 3.2.8 on 2023-10-20 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0207_auto_20231020_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise_email_conf',
            name='sender',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
