# Generated by Django 3.2.8 on 2023-10-20 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0208_enterprise_email_conf_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise_email_conf',
            name='sender',
            field=models.CharField(default='', max_length=300),
        ),
    ]
