# Generated by Django 3.2.8 on 2023-10-22 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0209_alter_enterprise_email_conf_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='answer_to',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='email_title',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
