# Generated by Django 3.2.8 on 2023-10-22 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0210_auto_20231021_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enterprise',
            name='answer_to',
        ),
        migrations.RemoveField(
            model_name='enterprise',
            name='email_title',
        ),
    ]
