# Generated by Django 3.2.8 on 2023-10-22 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0211_auto_20231021_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='answer_to',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='email_title',
            field=models.CharField(default='', max_length=80),
        ),
    ]
