# Generated by Django 5.1.1 on 2026-03-19 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0208_merge_20231024_0902'),
        ('api', '0212_auto_20231021_2240'),
    ]

    operations = [
    ]
