# Generated by Django 5.1.1 on 2026-03-23 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0213_merge_20260319_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer_envelope_extend',
            name='answer_envelope_child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_extend', to='api.answer_envelope'),
        ),
        migrations.AlterField(
            model_name='form_consecutive',
            name='form_enterprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_padre', to='api.form_enterprise'),
        ),
        migrations.AlterField(
            model_name='form_field_consecutive',
            name='form_field_get',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_padre', to='api.form_field'),
        ),
        migrations.CreateModel(
            name='Enterprise_Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.enterprise')),
                ('field_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.field_type')),
            ],
            options={
                'db_table': 'api_enterprise_attempt',
            },
        ),
    ]
