# Generated by Django 5.1.1 on 2026-03-25 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0214_alter_answer_envelope_extend_answer_envelope_child_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise_plans',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.plans'),
        ),
        migrations.AddField(
            model_name='plans',
            name='feature_db_segmented',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plans',
            name='feature_documents',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plans',
            name='feature_field_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plans',
            name='feature_flows',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plans',
            name='feature_lists',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plans',
            name='feature_my_drive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plans',
            name='feature_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plans',
            name='feature_reports',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plans',
            name='feature_roles',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plans',
            name='feature_statistics',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plans',
            name='feature_visits',
            field=models.BooleanField(default=False),
        ),
    ]
