# Generated by Django 5.1.1 on 2026-04-02 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0215_enterprise_plans_plan_plans_feature_db_segmented_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apis_Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.IntegerField()),
                ('service', models.IntegerField()),
                ('token', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('state', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.enterprise')),
            ],
        ),
        migrations.CreateModel(
            name='Apis_Config_Params',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('param_type', models.IntegerField()),
                ('required', models.BooleanField(default=False)),
                ('value', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('state', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('apis_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.apis_config')),
            ],
        ),
    ]
