# Generated by Django 5.1.1 on 2026-05-09 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0216_apis_config_apis_config_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_enterprise',
            name='digital_ia_state',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='form_enterprise',
            name='digital_ia_status',
            field=models.IntegerField(default=0),
        ),
    ]
