# Generated by Django 5.1.1 on 2026-05-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0217_form_enterprise_digital_ia_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AI_Knowledge_Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200, unique=True)),
                ('field_type_id', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('state', models.BooleanField(default=True)),
            ],
        ),
    ]
