from django.urls import path
from api import tests, views
#from django.urls import re_path
#from rest_framework import permissions
#from drf_yasg.views import get_schema_view
#from drf_yasg import openapi
from api.controllers import (
    api as _api,
    api_v2 as _external,
    admin,
    answer,
    associate_form,
    dashboard,
    device,
    enroll,
    enterprise,
    envelope,
    form,
    geoportal,
    inbox,
    notification,
    parameter,
    plataform,
    points,
    public,
    routing,
    site,
    system_log,
    traceability,
    user,
    plans,
    task,
    visits,
    contacts
)

#schema_view = get_schema_view(
#   openapi.Info(
#      title="MELMAC API",
#      default_version='v1',
#      description="Servicios Melmac",
#      terms_of_service="https://melmac.co/legal",
#      contact=openapi.Contact(email="hola@melmac.co"),
#      license=openapi.License(name="BSD License"),
#   ),
#   public=True,
#   #permission_classes=(permissions.AllowAny,),
#)

urlpatterns = [
    path('permits/', admin.PermitList.as_view()),
    path('permits/group/', admin.PermitListGrouped.as_view()),
    path('permits/<int:pk>/', admin.PermitDetail.as_view()),
    path('permits_role/<int:role>/', admin.PermitRoleList.as_view()),
    path('permits/ent/<int:pk>/', admin.PermitEntList.as_view()),

    path('role/', admin.RoleList.as_view()),
    path('role/<int:pk>/', admin.RoleDetail.as_view()),
    path('device_type/', device.TypeDeviceList.as_view()),
    path('device_type/<int:pk>/', device.TypeDeviceDetail.as_view()),

    path('start_app/', views.start_app),
    path('delete/duplicates/', views.delete_duplicates),

    # --- Files Detected Control ---
    path('control/<str:answer>/<int:consecutive>/<str:email>/', views.detected_trace),
    # Site
    path('login/', site.login),
    path('signup/', site.signup),
    path('landingform/', site.create_user_landing),
    path('logout/', site.logout),
    path('login_validate/', site.login_validate),
    path('register/', site.register),
    path('recovery_pass/', site.recovery_pass),
    path('send_token/', site.send_token),
    path('send_token_email/', notification.send_token_email),
    path('get_phone/', site.get_phone),
    path('validate_token/', site.validate_token),
    path('verificate_user/', site.verificate_user),
    path('verificate_phone/', site.verificate_phone),
    path('get_idCard/', site.get_idCard),
    path('update_profile/', site.update_profile),
    path('enrolment_user/', site.enrolment_user),
    path('enrolment_user_document/', site.enrolment_user_document),
    path('enrolment_user_validate/', site.enrolment_user_validate),
    path('verification_follow_user/', site.verification_follow_user),
    path('device_info_user/', site.device_info_user),
    path('update_gps_battery/', site.update_gps_battery),
    path('get_token_auth_ani/', site.get_token_auth_ANI),
    path('api_permission_list/', site.api_permission_list),
    path('api_data_ANI/<int:document>/', site.api_data_ANI),
    # User
    path('user/<int:enterprise>/', user.UserEnterpriseApiList.as_view()),
    path('user/<int:enterprise>/<int:pk>/', user.UserEnterpriseApiDetail.as_view()),
    path('get_role/<int:enterprise>/', user.get_role),
    path('user/notification/<int:pos>/', user.get_notifications),
    path('user/notification/status/', user.set_notification_status),
    # Contacts
    path('contacts/', contacts.ContactApiList.as_view()),
    path('contacts/<int:pk>/', contacts.ContactApiDetail.as_view()),
    # Massive Users
    path('massive-users/', user.MassiveUser.as_view()),
    path('massive-users/<int:pk>/error/', user.MassiveUserErrors.as_view()),
    # Massive Answer
    path('massive-answer/', answer.MassiveFormAsnwer.as_view()),
    # Traceability
    path('traceability/', traceability.TraceabilityList.as_view()),
    path('traceability/enterprise/<int:pk>/', traceability.TraceabilityList.as_view()),
    path('traceability/get_txt/', traceability.TraceabilityList.as_view()),
    path('traceability/add/', traceability.add),
    path('traceability/service/', traceability.trace_service),
    path('traceability/user/', traceability.trace_user),
    path('traceability/user_offline/', traceability.trace_user_offline),
    # Form
    path('form/', form.FormList.as_view()),
    path('form/<int:state>/', form.FormList.as_view()),
    path('form/delete/<int:pk>/', form.delete),
    path('form/activate/', form.activate),
    path('form/list/<int:consecutive>/', form.get_form),
    path('form/detail/<int:form>/', form.get_detail),
    path('form/send/<int:enterprise>/', form.get_send_form),
    path('form/share_forwarding/<int:form>/', form.share_forwarding),
    path('form/share_forwarding_all/', form.share_forwarding_all),
    path('form/data/<int:form>/', form.get_data_form),
    path('form/data/<int:form>/<int:consecutive>/', form.get_data_form),
    path('form/data/<int:form>/<int:consecutive>/<int:answer>/', form.get_data_form),
    path('form/consecutive/', form.add_consecutive),
    path('form/sequence/<int:form>/', form.get_sequence),
    path('form/sequence/<int:form>/<int:answer>/', form.get_sequence),
    path('form/consecutive/data/<int:form>/', form.get_data_consecutive),
    path('form/field/<int:form>/', form.get_field_form),
    path('form/field/<int:form>/<int:field_type>/', form.get_field_type),
    path('form/data/consecutive/all/', form.get_all_data_consecutive),
    path('form/data/fields/all/', form.get_all_data_fields),
    path('form/data/count_forms_sync/', form.count_forms_sync),
    #path('approvingAcept/', form.approving_acept),
    path('logs_form/', form.logs_form),
    # Public Docs
    path('form/link/', form.update_link),
    path('form/share/', form.share_document),
    path('resend_data/', form.resend_data),
    path('form/public/<str:token>/', form.get_form_token),
    path('form/public/pdf/<str:token>/<str:idUser>/', form.get_pdf_token),
    path('form/public/enterprise/<str:token>/', form.get_enterprise_token),
    path('form/public/<str:token>/<int:consecutive>/<int:current>/', form.get_form_token),
    path('form/public/<str:token>/<int:consecutive>/<int:current>/<int:answer>/', form.get_form_token),
    path('form/public/answer/<str:token>/', answer.create_public_answer),
    path('public/trace_doc/', answer.get_sign_info),
    # Digital
    path('form/digital/<int:pk>/', form.DigitalDetail.as_view()),
    path('form/digital/pdf/<int:pk>/', form.get_pdf),
    # Form Associate
    path('form/associate/<int:form>/<int:option>/', associate_form.AssociateList.as_view()),
    path('form/associate/<int:form>/<int:option>/<int:id>/', associate_form.AssociateList.as_view()),
    # Answer
    path('inbox/', inbox.InboxList.as_view()),
    path('inbox/<int:state>/', inbox.InboxList.as_view()),
    path('answer/', answer.AnswerList.as_view()),
    path('answer/<int:state>/', answer.AnswerList.as_view()),
    path('answer/<int:consecutive>/<int:pk>/', answer.AnswerDetail.as_view()),
    path('answer/pdf/<int:consecutive>/<int:pk>/', answer.get_pdf),
    path('answer/pdf/document/<int:consecutive>/<int:pk>/<int:type_doc>/', answer.get_pdf_external),
    path('answer/pdf/digital/<int:consecutive>/<int:pk>/', answer.get_digital_pdf),
    path('answer/pdf/digital/temporal/<int:pk>/', answer.get_temporal_pdf),
    path('answer/pdf/digital/temporal/movil/', answer.get_temporal_pdf_movil),
    path('answer/pdf/digital/temporal/<int:pk>/<str:token>/', answer.get_temporal_pdf),
    path('answer/pdf/to/zip/<int:pk>/', answer.get_digital_pdf_to_zip),
    path('answer/form/<int:form>/', answer.AnswerFormList.as_view()),
    path('answer/form/consecutive/<int:form>/', answer.AnswerFormConsecutiveList.as_view()),
    path('answer/excel/<int:consecutive>/<int:pk>/', answer.export_as_excel),
    path('answer/excel/document/', answer.export_as_excel_document),
    path('answer/zip/pdf/document/', answer.export_as_zip_pdf_document),
    path('answer/zip/pdf/list/', answer.get_massive_zip),
    path('answer/unique/validate/', answer.unique_validate),
    path('answer/unique/state/', answer.get_unique_state),
    # Device
    path('devices/', device.DeviceList.as_view()),
    path('devices/<int:pk>/', device.DeviceDetail.as_view()),
    path('devices/data/', device.DeviceData.as_view()),
    # Massive Devices
    path('massive-devices/', device.MassiveDevice.as_view()),
    path('massive-devices/<int:pk>/error/', device.MassiveDeviceErrors.as_view()),
    # Public
    path('theme_list/', public.get_theme),
    path('identification/', public.get_type_identification),
    path('role_list/', public.get_role),
    path('role_list/follow/', public.get_follow_role),
    path('user_list/', public.get_user),
    path('user_list/<int:all>/', public.get_user),
    path('get_user_role/', public.get_user_role),
    path('user_geo_list/', public.get_user_geo),
    path('user_data_token/', public.get_user_data_token),
    path('admin_list/', public.get_admin),
    path('historical/<int:pk>/', public.get_historical),
    path('country_list/', public.get_countries),
    path('city_list/', public.get_cities),
    path('value_parameter_list/', public.get_value_parameter),
    path('detail_restritive_list/', public.get_detail_restritive_list),
    # Enterprise
    path('enterprise/', enterprise.EnterpriseList.as_view()),
    path('enterprise/emails_general/', enterprise.email_enterprise_general),
    path('enterprise/detail/', enterprise.EnterpriseDetail.as_view()),
    path('enterprise/<int:pk>/', enterprise.EnterpriseList.as_view()),
    path('enterprise/theme/', enterprise.update_theme),
    path('enterprise/acronym_list/', enterprise.acronym_list),
    path('enterprise/test_email/', enterprise.test_email),
    path('enterprise/test_email_send/', enterprise.test_email_send),
    path('enterprise/save_email/', enterprise.save_email),
    # Enrolment
    path('get_token/', notification.Enrolment.token),
    path('get_video_match/', notification.Enrolment.video_match),
    path('get_image_match/', notification.Enrolment.image_match),
    path('get_ocr/', notification.Enrolment.ocr),
    path('authorization/', notification.Enrolment.authorization),
    path('enroll/', enroll.EnrollList.as_view()),
    path('enroll/<int:pk>/', enroll.EnrollDetail.as_view()),
    path('enroll/pdf/<int:pk>/', enroll.get_pdf),
    path('get_image_match_form/', notification.Enrolment.image_match_form),
    # Dashboard
    path('data_statistics/indicator/<int:option>/', dashboard.get_indicator),
    path('data_statistics/graph/<int:option>/', dashboard.get_graph),
    # Routing
    path('routing/normalize_test/', routing.normalizer_test),
    path('routing/download_file/', routing.generate_file_from_route),
    # Route Massive
    path('routes/', routing.RouteList.as_view()),
    path('routes/all/', routing.get_address_processes),
    path('routes/<int:pk>/', routing.get_address_process),
    path('routes/generate/', routing.generate_route_services),
    path('routes/change/', routing.change_location_to_route),
    path('routes/assign/', routing.assign_messagers),
    path('get_field_workers/', public.get_field_workers),
    path('services/', routing.services_monitor),
    path('services/<int:pk>/', routing.services_monitor_detail),
    path('service_location/<int:pk>/trace/', routing.get_location_trace),

    path('routes/status/<int:pk>/', routing.check_status),
    # Project
    path('projects/', routing.ProjectList.as_view()),
    path('projects/<int:pk>/', routing.ProjectDetail.as_view()),
    # Location
    path('locations/', routing.LocationList.as_view()),
    path('locations/<int:pk>/', routing.LocationDetail.as_view()),
    path('list_services/', routing.list_services),
    path('route_services/', routing.route_services),
    path('change_state/', routing.change_state),
    path('route_services_offline/', routing.route_services_offline),
    # Points
    path('points/', points.load_points),
    path('points/status/', points.check_status_points),
    # Plataform
    path('plataform/', plataform.PlataformList.as_view()),
    path('plataform/<int:pk>/', plataform.PlataformDetail.as_view()),
    # GeoPortal
    path('geoportal/', geoportal.GeoPortalPointList.as_view()),
    path('geoportal/answer/<int:position>/', geoportal.GeoPortalAnswerList.as_view()),
    path('geoportal/user/', geoportal.FollowUserDetail.as_view()),
    path('geoportal/status/', geoportal.check_status_points),
    # Parameter
    path('parameter/', parameter.ParameterList.as_view()),
    path('parameter/<int:pk>/', parameter.ParameterDetail.as_view()),
    # API
    path('api/', _api.get_api_list),
    path('api/list/', _api.ApiEnterpriseDetail.as_view()),
    path('api/detail/list/', _api.ApiEnterpriseList.as_view()),
    path('forward_handwritten_pdf/', form.forward_handwritten_pdf),
    path('list_handwritten_pdf/', form.list_handwritten_pdf),
    # System Log
    path('system/log/', system_log.get_logs),
    # Envelope
    path('envelope/', envelope.EnvelopeList.as_view()),
    path('envelope/fields/', envelope.get_fields),
    path('migrate_form/', form.migrate_envelope),
    path('envelope/fill_out/<int:option>/<str:answer>/<str:token>/', envelope.get_envelope_token),
    path('envelope/answer/', envelope.envelope_answer),
    path('envelope/approve/', envelope.envelope_approve),
    path('envelope/verified/', envelope.envelope_verified),
    path('envelope/checker/', envelope.envelope_checker),
    path('envelope/checker/file/', envelope.checker_file_verified),
    path('envelope/answer/public/contact/', envelope.envelope_answer_public_contact),
    # Plans
    path('create_plan/', plans.create_plan),
    path('list_plan/', plans.list_plan),
    path('list_service_plan/', plans.list_service_plan),
    path('list_item_plan/', plans.list_item_plan),
    path('create_service_plan/', plans.create_service_plan),
    path('list_home_item_user/', plans.list_home_item_user),
    #Task
    path('list_task_user/', task.list_task_user),
    path('change_state_task/', task.change_state_task),
    path('list_history_task/', task.list_history_task),
    path('list_task/', task.list_task),
    path('list_task_all/', task.list_task_all),
    path('create_task/', task.create_task),
    path('list_form_answer_task/', task.list_form_answer_task),
    path('list_trazability_task/', task.list_trazability_task),
    path('detail_task/', task.detail_task),
    path('document_task/', task.document_task),


    #visits
    path('list_proyect/', visits.list_proyect),
    path('delete_list_proyect/', visits.delete_list_proyect),
    path('list_sub_proyect/', visits.list_sub_proyect),
    path('list_programming/', visits.list_programming),
    path('create_proyect_task/', visits.create_proyect_task),
    path('create_sub_proyect/', visits.create_sub_proyect),
    path('list_sub_proyect_unit/', visits.list_sub_proyect_unit),
    path('programming_available/', visits.programming_available),
    path('list_proyect_subproyect/', visits.list_proyect_subproyect),

    # Enterprise Token
    path('enterprise/public/<str:token>/', enterprise.get_enterprise_token),
    path('enterprise/public/share/<str:token>/<str:phones>/<str:emails>/<str:semail>/<str:sSms>/<str:sWhatsapp>/<str:idForm>/', form.send_public_share),

]

#Urls API externa
urlpatterns += [
    path('api/v2/auth/login/', _external.get_token_login),
    path('api/v2/auth/set/', _external.set_token),
    path('api/v2/service/get_form/', _external.get_form_api),
    path('api/v2/service/get_form/<int:form>/', _external.get_form_id),
    path('api/v2/service/get_form_answer/<int:form>/', _external.get_form_answer_id),
    path('api/v2/service/post_form/', _external.post_form),
    path('api/v2/service/create_share_document/', _external.create_share_document),
    #path('document/swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    #path('document/redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]