export const types = [
    {
        label: 'Alfanumérico',
        field_type: '1',
        icon: '',
        validate: {},
        group: 1,
    },
    {
      label: 'Archivo',
      field_type: '8',
      icon: '',
      group: 1,
    },
    {
      label: 'Captura',
      field_type: '9',
      icon: '',
      group: 1,
    },
    {
      label: 'Dirección',
      field_type: '25',
      icon: '',
      group: 1,
    },
    {
      label: 'Fecha',
      field_type: '4',
      icon: '',
      group: 1,
    },
    {
      label: 'Firma biométrica facial',
      field_type: '10',
      icon: '',
      group: 3,
    },
    {
      label: 'Firma con cédula',
      field_type: '18',
      icon: '',
      group: 3,
    },
    {
      label: 'Firma electrónica OTP',
      field_type: '22',
      icon: '',
      group: 3,
    },
    {
      label: 'Firma manuscrita',
      field_type: '7',
      icon: '',
      group: 3,
    },
    {
      label: 'Hora',
      field_type: '19',
      icon: '',
      group: 1,
    },
    {
      label: 'Información',
      field_type: '14',
      icon: '',
      group: 2,
    },
    {
        label: 'Lista',
        field_type: '3',
        icon: '',
        values: [],
        group: 2,
    },
    {
        label: 'Llave y valores',
        field_type: '26',
        icon: '',
        values: [],
        group: 2,
    },
    {
      label: 'Moneda',
      field_type: '16',
      icon: '',
      group: 2,
    },
    {
      label: 'Múltiple',
      field_type: '13',
      icon: '',
      values: [],
      group: 2,
    },
    {
      label: 'NIT',
      field_type: '20',
      icon: '',
      values: {},
      group: 2,
    },
    {
        label: 'Numérico',
        field_type: '2',
        icon: '',
        validate: {},
        group: 1,
    },
    {
      label: 'Número de documento',
      field_type: '11',
      icon: '',
      validate: {},
      group: 2,
    },
    {
      label: 'Número de serie',
      field_type: '24',
      icon: '',
      values: [],
      group: 2,
    },
    {
      label: 'País',
      field_type: '23',
      icon: '',
      validate: {},
      group: 2,
    },
    {
        label: 'Solo letras',
        field_type: '5',
        icon: '',
        validate: {},
        group: 1,
    },
    {
      label: 'Tabla',
      field_type: '17',
      icon: '',
      fields: [],
      group: 2,
    },
    {
        label: 'Texto',
        field_type: '6',
        icon: '',
        validate: {},
        group: 1,
    },
    {
        label: 'Ubicación',
        field_type: '15',
        icon: '',
        group: 1,
    },
    {
      label: 'Única',
      field_type: '12',
      icon: '',
      values: [],
      group: 2,
    },
    {
      label: 'Separador de Sección',
      field_type: '27',
      icon: '',
      group: 4,
    }
]

export const variables = {
  usual_fields: 'usual_fields',
  special_fields: 'special_fields',
  signature_fields: 'signature_fields',
  general_config_fields: 'general_config_fields'
}
